### ISSUE TITLE
Pure ImageService3

### ISSUE THREAD

**Issue by ra-magnus-welander** [digirati-co-uk/iiif-net#8]
Hi!

We're looking at using this class library in our own IIIF Server implementation. It looks really promising, even though it is not complete. 

One thing that I'm stumbling on right now is that there is an implementation called ImageService2 which has some characteristics of ImageService2 ("@id" and "@type" instead of "id" and "type") and some of ImageService3 (a single "profile" string).

What I really need is a pure ImageService3 implementation. I think I could manage to supply one. Are you interested in pull requests?

Regards,
Magnus

**Comment by donaldgray** [comment]
Hi @ra-magnus-welander ,

Apologies for the slow response, the notification must have escaped me.

This library originated from a couple of different implementations that we have for various internal projects, as you've noticed it's almost there but there are still some omissions. To date we've only used this with ImageService2, which is why 3 isn't fully implemented. 

However, we're more than happy to accept pull requests for functionality that is missing.

**Comment by donaldgray** [comment]
Closing as ImageService3 added in PR https://github.com/digirati-co-uk/iiif-net/pull/10
